name: Build and Deploy Storybook

on:
  push:
    branches: [main]
    paths:
      # Set path filter pickup all changes in src/ and .storybook/
      - 'src/**'
      - '.storybook/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      # Pins Yarn to the "packageManager" version in package.json
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build Storybook
        run: yarn storybook:build
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
